jobs:
- steps:
  - name: git-clone
    run: |
      #!/usr/bin/env bash
      export SUBDIR="source"
      echo "git cloning url: $REPO_URL version $PULL_PULL_SHA to dir: $SUBDIR"
      git config --global --add user.name ${GIT_AUTHOR_NAME:-jenkins-x-bot}
      git config --global --add user.email ${GIT_AUTHOR_EMAIL:-jenkins-x@googlegroups.com}
      git config --global credential.helper store
      git clone $REPO_URL $SUBDIR
      cd $SUBDIR
      git checkout $PULL_PULL_SHA
      echo "checked out revision: $PULL_PULL_SHA to dir: $SUBDIR"
    uses: docker://gcr.io/jenkinsxio/builder-jx:2.1.142-761
  - name: setup-builder-home
    run: /bin/sh -c [ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home
    uses: docker://gcr.io/jenkinsxio/builder-jx:2.1.142-761
  - name: git-merge
    run: jx step git merge --verbose --baseSHA $(params.PULL_BASE_SHA) --sha $(params.PULL_PULL_SHA) --baseBranch $(params.PULL_BASE_REF)
    uses: docker://gcr.io/jenkinsxio/builder-jx:2.1.142-761
  - name: jx-variables
    run: |
      #!/usr/bin/env sh
      jx gitops variables
    uses: docker://gcr.io/jenkinsxio/jx-boot:3.1.28
  - name: build-make-linux
    run: |
      #!/bin/sh
      make linux
    uses: docker://gcr.io/jenkinsxio/builder-go:2.1.150-769
  - name: build-container-build
    run: |
      #!/busybox/sh
      source .jx/variables.sh
      cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
      /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
    uses: docker://gcr.io/kaniko-project/executor:debug-v1.3.0
  - name: promote-jx-preview
    run: |
      #!/usr/bin/env sh
      source /workspace/source/.jx/variables.sh
      jx preview create
    uses: docker://gcr.io/jenkinsxio/jx-preview:0.0.135
"on":
  pull_request: {}
  push:
    branches-ignore:
    - main
    - master
