jobs:
  pr:
    steps:
    - name: jx-variables
      run: jx gitops variables
      shell: sh
      uses: docker://gcr.io/jenkinsxio/jx-boot:3.1.28
    - name: build-make-linux
      run: make linux
      shell: sh
      uses: docker://gcr.io/jenkinsxio/builder-go:2.1.150-769
    - name: build-container-build
      run: |-
        source .jx/variables.sh
        cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
        /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
      shell: /busybox/sh
      uses: docker://gcr.io/kaniko-project/executor:debug-v1.3.0
    - name: promote-jx-preview
      run: |-
        source /workspace/source/.jx/variables.sh
        jx preview create
      shell: sh
      uses: docker://gcr.io/jenkinsxio/jx-preview:0.0.135
"on":
  pull_request: {}
  push:
    branches-ignore:
    - main
    - master
