jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: next-version
      uses: docker://gcr.io/jenkinsxio/jx-release-version:1.0.42
      with:
        entrypoint: bash -c 'VERSION=$(jx-release-version); echo $VERSION > VERSION'
    - name: jx-variables
      uses: docker://gcr.io/jenkinsxio/jx-boot:3.1.28
      with:
        entrypoint: sh -c 'jx gitops variables'
    - name: build-make-build
      uses: docker://gcr.io/jenkinsxio/builder-go:2.1.150-769
      with:
        entrypoint: /bin/sh -c 'make build'
    - name: build-container-build
      uses: docker://gcr.io/kaniko-project/executor:debug-v1.3.0
      with:
        entrypoint: /busybox/sh -c 'source .jx/variables.sh; cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json; /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION'
    - name: promote-changelog
      uses: docker://gcr.io/jenkinsxio/jx-changelog:0.0.13
      with:
        entrypoint: 'sh -c ''source /workspace/source/.jx/variables.sh; ; if [ -d \"/workspace/source/charts/$REPO_NAME\" ]; then; sed -i -e \"s/^version:.*/version: $VERSION/\" ./charts/$REPO_NAME/Chart.yaml; sed -i -e \"s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/\" ./charts/$REPO_NAME/values.yaml; sed -i -e \"s/tag:.*/tag: $VERSION/\" ./charts/$REPO_NAME/values.yaml;; else echo no charts; fi; ; git commit -a -m \"chore: release $VERSION\" --allow-empty; git tag -fa v$VERSION -m \"Release version $VERSION\"; git push origin v$VERSION; ; jx changelog create --version v${VERSION}'''
    - name: promote-helm-release
      uses: docker://gcr.io/jenkinsxio/jx-boot:3.1.28
      with:
        entrypoint: sh -c 'jx gitops helm release'
    - name: promote-jx-promote
      uses: docker://gcr.io/jenkinsxio/jx-promote:0.0.156
      with:
        entrypoint: sh -c 'source /workspace/source/.jx/variables.sh; jx promote -b --all-auto --timeout 1h --no-poll'
"on":
  push:
    branches:
    - main
    - master
